In [1]:
import numpy as np

In [4]:
a= np.arange(10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = np.arange(12)
b=b.reshape([3,4])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
b[:,1]

array([1, 5, 9])

In [11]:
b[0:2,1:3]=0

In [12]:
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])